name = "eremeevca"
account_id = "18352558d044bc81dd45e0fb6956dd64"
workers_dev = false
compatibility_date = "2022-04-05"
main = "eremeevca/index.js"

[site]
bucket = "./public"

[env.production]
workers_dev = false
# The route pattern your Workers application will be served at

[env.development]
workers_dev = true
name = "eremeevca-stage"
