name = "eremeevca"
type = "webpack"
workers_dev = true
route = "eremeev.ca/*"

[site]
bucket = "./public"
entry-point = "eremeevca"

[env.production]
# The route pattern your Workers application will be served at
route = "eremeev.ca/*"
account_id = "18352558d044bc81dd45e0fb6956dd64"

[env.development]
route = "dev.eremeev.ca/*"