name: Deploy to cloudflare workers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # Step 1 - Checks-out the repo
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

        # Step 3 - Clean and don't fail
      # - name: Clean public directory
      #  run: rm -rf public

        # Step 4 - Builds the site using the latest version of Hugo
      - name: Build
        run: hugo --minify

        # Step 5 - Publish the generated website to cloudflare Workers
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
            USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: echo "*** pre command ***"
          postCommands: |
            echo "*** post commands ***"
            wrangler publish --env production
            echo "******"
